name: test
on: [workflow_call]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Lint code for consistent style via Standard Ruby
        run: bundle exec standardrb

      - name: Run tests
        run: bundle exec rake test
